#!/usr/bin/env python

import sys
import rospy
from egh450_path_planning.path_planner import PathPlanner

if __name__ == '__main__':
	# Initialize
	rospy.init_node('egh450_path_planning', anonymous=True)

	nav = None

	try:
		nav = PathPlanner()

		rospy.loginfo("[NAV] Path planner node running")

		# Loop here until quit
		rospy.spin()
	except rospy.ROSInterruptException:
		rospy.loginfo("[NAV] Path planner shutting down")
	finally:
		# Shutdown if nav was started successfully
		if nav is not None:
			nav.shutdown()
